apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webbuchhaltung.name" . }}-config
  labels: {{- include "webbuchhaltung.labels" . | nindent 4 }}
data:
  CORS_ORIGINS: {{ .Values.config.corsOrigins | quote }}
  STORAGE_ROOT: {{ .Values.config.storageRoot | quote }}
  BOOTSTRAP_SKR_VARIANT: {{ .Values.config.bootstrapSkrVariant | quote }}
  BOOTSTRAP_MANDANT_NAME: {{ .Values.config.bootstrapMandantName | quote }}
