apiVersion: v1
kind: Secret
metadata:
  name: {{ include "webbuchhaltung.name" . }}-secret
  labels: {{- include "webbuchhaltung.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.secrets.secretKey | quote }}
  DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  ANTHROPIC_API_KEY: {{ .Values.secrets.anthropicApiKey | quote }}
