apiVersion: v1
kind: Service
metadata:
  name: {{ include "webbuchhaltung.name" . }}-backend
  labels: {{- include "webbuchhaltung.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "webbuchhaltung.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
