"""initial_schema

Revision ID: a5138fdc66fa
Revises:
Create Date: 2026-05-09 12:00:23.104620

"""

from typing import Sequence, Union

from alembic import op  # type: ignore[attr-defined]
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a5138fdc66fa"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mandants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("steuernummer", sa.String(length=50), nullable=True),
        sa.Column("ust_id", sa.String(length=20), nullable=True),
        sa.Column("datev_beraternummer", sa.String(length=10), nullable=True),
        sa.Column("datev_mandantennummer", sa.String(length=10), nullable=True),
        sa.Column("fiscal_year_start", sa.Integer(), nullable=False),
        sa.Column(
            "skr_variant",
            sa.Enum("skr03", "skr04", "skr07", name="skr_variant_enum"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tax_keys",
        sa.Column("code", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("tax_rate", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column(
            "tax_type",
            sa.Enum(
                "USt",
                "VSt",
                "steuerfrei",
                "§13b",
                "keine",
                "UStfrei",
                name="tax_type_enum",
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "accounting_periods",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("mandant_id", sa.Uuid(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("open", "locked", "archived", name="period_status_enum"),
            nullable=False,
        ),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["mandant_id"],
            ["mandants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "mandant_id", "year", "month", name="uq_period_mandant_year_month"
        ),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("mandant_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("table_name", sa.String(length=64), nullable=False),
        sa.Column("record_id", sa.Uuid(), nullable=False),
        sa.Column(
            "action",
            sa.Enum("insert", "update", "delete", name="audit_action_enum"),
            nullable=False,
        ),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("change_summary", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mandant_id"],
            ["mandants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "booking_groups",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("mandant_id", sa.Uuid(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["mandant_id"],
            ["mandants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "booking_sequences",
        sa.Column("mandant_id", sa.Uuid(), nullable=False),
        sa.Column("next_value", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mandant_id"],
            ["mandants.id"],
        ),
        sa.PrimaryKeyConstraint("mandant_id"),
    )
    op.create_table(
        "chart_of_accounts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("mandant_id", sa.Uuid(), nullable=False),
        sa.Column("account_number", sa.String(length=4), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("account_class", sa.String(length=10), nullable=False),
        sa.Column("tax_type", sa.String(length=50), nullable=True),
        sa.Column(
            "skr_variant",
            sa.Enum("skr03", "skr04", "skr07", "custom", name="skr_source_enum"),
            nullable=False,
        ),
        sa.Column("is_custom", sa.Boolean(), nullable=False),
        sa.Column("private_share_percent", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "private_share_percent BETWEEN 0 AND 100", name="ck_coa_private_share"
        ),
        sa.ForeignKeyConstraint(
            ["mandant_id"],
            ["mandants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "mandant_id", "account_number", name="uq_coa_mandant_number"
        ),
    )
    op.create_table(
        "user_mandants",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("mandant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("admin", "bookkeeper", "readonly", name="user_role_enum"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["mandant_id"],
            ["mandants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "mandant_id"),
    )
    op.create_table(
        "bookings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("mandant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "booking_type",
            sa.Enum("bank", "entry", name="booking_type_enum"),
            nullable=False,
        ),
        sa.Column("booking_group_id", sa.Uuid(), nullable=True),
        sa.Column("parent_booking_id", sa.Uuid(), nullable=True),
        sa.Column("reversal_of_id", sa.Uuid(), nullable=True),
        sa.Column("date_booking", sa.Date(), nullable=False),
        sa.Column("date_tax", sa.Date(), nullable=True),
        sa.Column("amount_cents", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("document_number", sa.String(length=12), nullable=True),
        sa.Column(
            "status",
            sa.Enum("draft", "posted", "reversed", name="booking_status_enum"),
            nullable=False,
        ),
        sa.Column("notes", sa.String(length=60), nullable=True),
        sa.Column("entry_number", sa.BigInteger(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("coa_id", sa.Uuid(), nullable=True),
        sa.Column("counter_coa_id", sa.Uuid(), nullable=True),
        sa.Column("tax_rate", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("tax_amount_cents", sa.BigInteger(), nullable=True),
        sa.Column("tax_key_code", sa.Integer(), nullable=True),
        sa.Column("contact_id", sa.Uuid(), nullable=True),
        sa.Column("bank_account_id", sa.Uuid(), nullable=True),
        sa.Column("recipient_name", sa.String(length=255), nullable=True),
        sa.Column("foreign_bank_account", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "booking_type != 'entry' OR (coa_id IS NOT NULL AND counter_coa_id IS NOT NULL)",
            name="ck_booking_entry_accounts",
        ),
        sa.CheckConstraint(
            "status != 'posted' OR entry_number IS NOT NULL",
            name="ck_booking_posted_has_number",
        ),
        sa.CheckConstraint("amount_cents > 0", name="ck_booking_amount_positive"),
        sa.ForeignKeyConstraint(
            ["booking_group_id"],
            ["booking_groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["coa_id"],
            ["chart_of_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["counter_coa_id"],
            ["chart_of_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["mandant_id"],
            ["mandants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_booking_id"],
            ["bookings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reversal_of_id"],
            ["bookings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tax_key_code"],
            ["tax_keys.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###

    # PostgreSQL-only: GoBD immutability trigger on bookings (asyncpg requires one statement per execute)
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute(
            sa.text("""
            CREATE OR REPLACE FUNCTION prevent_posted_booking_update()
            RETURNS TRIGGER AS $$
            BEGIN
                IF OLD.status = 'posted' AND NEW.status != 'reversed' THEN
                    RAISE EXCEPTION 'Cannot modify a posted booking. Use reversal instead.';
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql
        """)
        )
        op.execute(
            sa.text("DROP TRIGGER IF EXISTS booking_immutability_check ON bookings")
        )
        op.execute(
            sa.text("""
            CREATE TRIGGER booking_immutability_check
                BEFORE UPDATE ON bookings
                FOR EACH ROW EXECUTE FUNCTION prevent_posted_booking_update()
        """)
        )


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute(
            sa.text("DROP TRIGGER IF EXISTS booking_immutability_check ON bookings")
        )
        op.execute(sa.text("DROP FUNCTION IF EXISTS prevent_posted_booking_update"))
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bookings")
    op.drop_table("user_mandants")
    op.drop_table("chart_of_accounts")
    op.drop_table("booking_sequences")
    op.drop_table("booking_groups")
    op.drop_table("audit_log")
    op.drop_table("accounting_periods")
    op.drop_table("users")
    op.drop_table("tax_keys")
    op.drop_table("mandants")
    # ### end Alembic commands ###
